# Generated by Django 4.2.13 on 2024-07-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'статья'), ('NE', 'новость')], default='NE', max_length=2),
        ),
    ]
